openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
  description: A simple API to return Hello World
paths:
  /:
    get:
      summary: Return Hello World
      operationId: getHelloWorld
      responses:
        '200':
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
servers:
  - url: http://localhost:5000
    description: Local server